version: '3'
services:
  resumeapp:
    container_name: test_app
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - /app/build
      - .:/app
    ports:
      - ${PORT}:${PORT} 